// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {config} from '../models';
import {slidev} from '../models';

export function ApplyTheme(arg1:string,arg2:string):Promise<void>;

export function CheckForUpdates():Promise<updater.UpdateInfo>;

export function CreateProject(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function GetSettings():Promise<config.Config>;

export function GetSlidevUrl():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InsertPage(arg1:string,arg2:number,arg3:string):Promise<void>;

export function ListProjects():Promise<Array<slidev.Project>>;

export function ReadSlides(arg1:string):Promise<string>;

export function SaveSettings(arg1:config.Config):Promise<void>;

export function SaveSlides(arg1:string,arg2:string):Promise<void>;

export function StartSlidevServer(arg1:string):Promise<string>;

export function UpdatePage(arg1:string,arg2:number,arg3:string):Promise<void>;
