// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetServerPort():Promise<string>;

export function GetSettings():Promise<config.Config>;

export function Greet(arg1:string):Promise<string>;

export function SaveSettings(arg1:config.Config):Promise<void>;
