// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function GenerateOutline(arg1) {
  return window['go']['main']['App']['GenerateOutline'](arg1);
}

export function GenerateSlides(arg1, arg2) {
  return window['go']['main']['App']['GenerateSlides'](arg1, arg2);
}

export function GetServerPort() {
  return window['go']['main']['App']['GetServerPort']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSlidevUrl() {
  return window['go']['main']['App']['GetSlidevUrl']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ReadSlides() {
  return window['go']['main']['App']['ReadSlides']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveSlides(arg1) {
  return window['go']['main']['App']['SaveSlides'](arg1);
}

export function StartSlidevServer() {
  return window['go']['main']['App']['StartSlidevServer']();
}
