// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {ai} from '../models';
import {config} from '../models';
import {slidev} from '../models';

export function CheckForUpdates():Promise<updater.UpdateInfo>;

export function CreateProject(arg1:string):Promise<void>;

export function GenerateOutline(arg1:string):Promise<Array<ai.OutlineItem>>;

export function GenerateSlides(arg1:string,arg2:Array<ai.OutlineItem>):Promise<void>;

export function GetServerPort():Promise<string>;

export function GetSettings():Promise<config.Config>;

export function GetSlidevUrl():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListProjects():Promise<Array<slidev.Project>>;

export function ReadSlides():Promise<string>;

export function SaveSettings(arg1:config.Config):Promise<void>;

export function SaveSlides(arg1:string):Promise<void>;

export function StartSlidevServer():Promise<string>;
