// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyTheme(arg1, arg2) {
  return window['go']['main']['App']['ApplyTheme'](arg1, arg2);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSlidevUrl() {
  return window['go']['main']['App']['GetSlidevUrl']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InsertPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['InsertPage'](arg1, arg2, arg3);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ReadSlides(arg1) {
  return window['go']['main']['App']['ReadSlides'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveSlides(arg1, arg2) {
  return window['go']['main']['App']['SaveSlides'](arg1, arg2);
}

export function StartSlidevServer(arg1) {
  return window['go']['main']['App']['StartSlidevServer'](arg1);
}

export function UpdatePage(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePage'](arg1, arg2, arg3);
}
